name: Deploy Angular Frontend

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install frontend dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # 4. Build Angular app
      - name: Build Angular app
        run: npm run build -- --output-path=dist/frontend --base-href=/ai-travel-planner/
        working-directory: ./frontend

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist/frontend
          force_orphan: true  # ensures a clean branch is created
          clean: true         # removes old files before deploying
